### ISSUE TITLE
Would you guys please publish the latest code to PyPI?

### ISSUE THREAD

**Issue by anzelpwj** [egnyte/python-egnyte#7]
Hi there,

It looks like your code on PyPI is from last year. Would you mind uploading the latest version of your code (looks like you've already declared this code to be 0.6) to PyPI? Preferably including the code change I had pushed ;)

Thank you,
Paul

**Comment by dsoloviov** [comment]
Hi Paul,

It's done, the new version (0.5.1) is now live on PyPI. Your contribution included :)
